### ISSUE TITLE
Grenades can be underhanded and have an animation for it.

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#114]
**Current state:**
By right clicking, you can underhand throw a grenade a short distance.
Issues:
When underhanding, your worldmodel T-poses, as there is no animation for underhanding. (depending on which build, the overhand throwing animation may be played)

**Suggested resolution:**
Create/import an underhanded throwing animation.

**Alternative resolution:**
1. Keep the overhand throwing animation and call it good enough.
2. Remove underhand throwing grenades as it is not parity.

**Comment by kassibuss** [comment]
Checked on the newest release we playtested on, seems like there are first/third person animations now, so close?

**Comment by kassibuss** [comment]
> > Checked on the newest release we playtested on, seems like there are first/third person animations now, so close?
> 
> are they unique underhanded animations? or are they just the same animation but used for underhanded throwing as well? also wasnt underhanded throwing disabled entirely

They are the same animations as the primary throwing. And no, it still worked

**Comment by kassibuss** [comment]
Close?

**Comment by kassibuss** [comment]
Closing, since underhanding nades has been removed with https://github.com/NeotokyoRebuild/neo/pull/714
