### ISSUE TITLE
NVGs should work as well as in OGNT

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#135]
This one is a little hard to quantify, but in rebuild there are fewer distinct shades of color on screen at all time.

map nt_tarmac_ctg 
sv_cheats 1
setpos -272.583618 552.612244 -475.968
setang 5.016034 -15.808

OG

![Image](https://github.com/user-attachments/assets/3756b6ab-e98b-4606-8e41-33b049b962d4)

Rebuild

![Image](https://github.com/user-attachments/assets/9bd50d6b-fc41-4661-91b0-41e8bf0c254d)

Let's call if "done" when:

1. Base color is dark grey instead of green
2. Highlights/lighter areas become whiter/lighter grey instead of darker

Does that make sense?

**Comment by AdamTadeusz** [comment]
So currently in ntre the vision is black-hot instead of white-hot, this issue will be fixed by flipping this. Looks like the green on the lighter end of the scale in the original is also a lighter shade of green than the current shade of green, though that perception may change after the flip.
![yttcfjh4v2u21](https://github.com/user-attachments/assets/5bbd740b-6e6f-417d-92a6-05594db303fe)

**Comment by kassibuss** [comment]
There are (cheat protected) cvar for the nightvision in the game, maybe changing the defaults to them will help get a closer look to OGNT?

```
mat_neo_nv_brightness                    : 0        : , "cheat"        : 
mat_neo_nv_contrast                      : 1        : , "cheat"        : 
mat_neo_nv_green_scale                   : 0        : , "cheat"        : Amount of green hue in nightvision.
mat_neo_nv_luminance                     : 0        : , "cheat"        : 
mat_neo_nv_startgamma                    : 2        : , "cheat"        : 
mat_neo_nv_targetgamma                   : 2        : , "cheat"        : 
```

**Comment by kassibuss** [comment]
This needs more testing but playing around with the base values a bit, I got it a bit closer to the OG NV. I didnt do the recon spot test. I am sure this is not 1:1, but I did it in like 5 minutes. Just something to get the ball rolling.
![image](https://github.com/user-attachments/assets/277789d7-dba5-447c-a41a-90a96c2a534a)
![20240803003433_1](https://github.com/user-attachments/assets/f6fe6cef-0e31-417d-9d17-5ff5a4bd32ce)
![image](https://github.com/user-attachments/assets/369fd568-16bb-4d24-b437-c59a87eddf1e)
