### ISSUE TITLE
Spectated players health points is communicated to spectators in real time

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#137]
Description:
When spectating a player, the amount of health showing up next to their name in the spectator overlay is slow to update, it's delayed by a few seconds. Or maybe I am misremembering and it never updates as long as you spectate them. But if I remember right, it does update, just slowly.
To reproduce:

spectate a player as they are taking damage.

Expected outcome: 

The HP of the player being spectated decreases as soon as they get hit

Actual outcome:

The HP stays the same for a few seconds or until you swap back and forth with another player.

**Comment by AdamTadeusz** [comment]
I think this is describing a bug where when you spectate someone, the hp you see next to their name in the spectator overlay is not their actual hp. Can be fixed by changing who is being spectated and then going back to that person afaik
