### ISSUE TITLE
Team score in team selection menu reflect W/L/T

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#139]
**Issue:**
When chosing team, the Score reflects the number of kills made by that team.

**Resolution:**
Score is not number of round wins, not kills made. 

![Image](https://github.com/user-attachments/assets/0d70285b-2f5e-4b92-ae2a-8ed1653cf0d8)

This has been resolved. TODO: find the PR.

**Comment by AdamTadeusz** [comment]
Possibly a duplicate of  #54?

**Comment by kassibuss** [comment]
fixed by https://github.com/NeotokyoRebuild/neo/pull/263
