### ISSUE TITLE
Actors dismember when heavily damaged

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#140]

**Comment by AdamTadeusz** [comment]
The exact values required to dismember have not been discovered yet, but the functionality is there. I guess an empirical analysis without testing bullets penetrating different surfaces to hit an actor would get us most of the way there, and then its just a case of worrying about bullets penetrating surfaces that have their damage modified not dismembering at exactly the right thresholds

**Comment by AdamTadeusz** [comment]
Came back to this and after doing some quick testing I noticed that both the lowest damage weapon in the game and the highest causes dismemberment. I guess we should therefore remove the dismember thresholds that are currently programmed in for parity, then close this, and then have a discussion about whether we want to re-introduce thresholds

**Comment by Rainyan** [comment]
Some rogue bikeshedding for posterity: we might want to consider implementing this as a likelihood that increases with the weapon base damage, so you could be seeing dismemberment with anything but it's more likely to occur with the heavy hitting guns.

**Comment by blaberry** [comment]
Moving this to QoL as it's certainly not parity.
