### ISSUE TITLE
Squads exist and you can swap between them

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#145]

**Comment by AdamTadeusz** [comment]
Squads already exist, and you can switch between them. Should we repurpose this issue to something like "Other players and their health in same squad is displayed on the HUD"?

**Comment by AdamTadeusz** [comment]
And since I don't think anybody likes the current squad members hud, what do you guys think about something like this 
![image](https://github.com/NeotokyoRebuild/neo/assets/44210793/608e1c46-7a19-42f7-8b6d-5a49cef76795)
?

**Comment by blaberry** [comment]
As long as it retains the same information as the current system (health, basically) I think it's a great idea. I'm curious what would work for pubs, though, just stacking the icons closer and closer?

**Comment by Agiel** [comment]
Instead of repurposing, should we close this in favor of #324? Or is there still work to do on the old style squad HUD?

**Comment by AdamTadeusz** [comment]
Still need to add the old style list, lets keep this open until then
