### ISSUE TITLE
Spectators able to see player outlines

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#146]
**Background**
When spectating the game, players currently have a team symbol centered on their torso to let people see where they are.

**Issue**
The team symbol provides very little detailed information about the living players, such as which animation state they're in or which direction they are looking in.

**Solution**
Draw an outline around players, allowing spectators and streamers to easily see which direction players are facing and which animation state they are in. This would let spectators and commentators during competetive games more easily ascertain what is going on.

**Comment by kassibuss** [comment]
fixed by https://github.com/NeotokyoRebuild/neo/pull/187 or?
