### ISSUE TITLE
Streamer Mode

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#150]
Requested features, preferably with individual toggles: 
- Hide Other Player names (Gives other players generic nicknames)
- Mute Players (ability to mute individual players in VC and Text)
- Hide any information related to Region/IP
- Profanity Filter (Could just be a general setting to toggle)
- Disable Gibs

**Comment by Rainyan** [comment]
As for gibs, we already have low violence settings natively at:

https://github.com/NeotokyoRebuild/neo/blob/e6d186b61bf35557143f9d85bb68a76fe5757c9c/mp/src/game/shared/util_shared.cpp#L852-L858

although I don't think we actually check the "human gibs" cvar at `CNEO_Player::SpawnDeadModel` currently. Probably we should do that.

Not sure whether I agree we low violence mode specifically tied into a streamer mode - one should probably not be streaming a first person shooter if they take issue with these things.
