### ISSUE TITLE
[DOC] Document how to enable menus from sourcemod plugin

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#154]

**Comment by nullsystem** [comment]
Need to change the title/description as this is about sourcemod.

**Comment by nullsystem** [comment]
Plugin menus works fine after adding "neo" to the whitelist. Here's how:
1. Go to directory `addons/sourcemod/gamedata/core.games` and you'll see `common.games.txt`
2. Create `custom` directory in that directory and copy `common.games.txt` over to there
3. Open `custom/common.games.txt` and scrolldown till you see "Which games support ShowMenu?" comment
4. Add `neo` to that supported list like this: `"game" "neo"`
