### ISSUE TITLE
Players can spawn despite insufficient spawn points on the map

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#209]

**Comment by AdamTadeusz** [comment]
flooding a map like nt_dimensions_test where there is only one spawn point per team with many bots, All the bots spawn in that one spawn point, so this was never an issue I don't think?

**Comment by kassibuss** [comment]
OTOH, I tried tetsu today, which has an issue of spawning players into the info_player_start when there isn't enough spawn points per player and the bots all seemed to spawn on the proper spawns, but inside each other. Maybe this isn't an issue as Zwia said?
