### ISSUE TITLE
Players can unstuck themselves from physics objects

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#212]
If this is even necessary? Maybe downprio and use SM unless it's a big issue.

**Comment by AdamTadeusz** [comment]
I don't think this is an issue. A player stuck on a prop can get themselves unstuck easily, and we are removing the lean stuff that changed the player hull size causing players getting stuck on staircases. There is the problem of supports getting stuck in the top part of a doorway when jumping but that has a separate issue I think open for it
