### ISSUE TITLE
Rounds are reset to zero upon pre-game ending.

### ISSUE THREAD

**Issue by StellaNova522** [NeotokyoRebuild/neo#222]
During comp, a warmup period is ran before everyone !ready ies up. This pregame DM has round counts and score and KDR, etc.

**issue:**
The score and round wins from DM should not stick around after the match properly starts

**Comment by nullsystem** [comment]
This is technically already the case, although will put this under the !ready mechanic PR + there was a slight bug to fix related to it anyway.
