### ISSUE TITLE
Picking up Grenades and Detpack

### ISSUE THREAD

**Issue by VantoNortim** [NeotokyoRebuild/neo#233]
If they fall with a certain orinetation their origin is below the floor so the raycast to check for clear LOS hits the floor before the player. Maybe the origin needs to be adjusted in the model?

**Comment by kassibuss** [comment]
Was this fixed? @VantoNortim

**Comment by VantoNortim** [comment]
> Was this fixed? @VantoNortim

Nope this is still an issue afaik

**Comment by AdamTadeusz** [comment]
https://github.com/user-attachments/assets/1479442c-83e4-411d-8bfb-26f9e019d297

Here's a video showcasing the problem. A grenade on nt_dimensions_test cannot be picked up if its z position is around 128, but the moment it is around 130 picking it up is not a problem
