### ISSUE TITLE
Clan tag - Left-side of name, right-side of teamname if all players same clantag

### ISSUE THREAD

**Issue by nullsystem** [NeotokyoRebuild/neo#267]
* Left-side of name in scoreboard, text chat, hover-name, etc...
* Right-side of team name in scoreboard, round win/lose, etc...
    * Only show if everyone in the team has the same tag
* New convar: `neo_clantag`
* Server-side convar to toggle: `neo_clantag_allow`

**Comment by nullsystem** [comment]
Do this after: https://github.com/NeotokyoRebuild/neo/pull/266 gets merge in. I think the duplicate checker postfix string from there can be reused to include clan tag prefix also.

**Comment by kassibuss** [comment]
Would this only be for comp?

**Comment by nullsystem** [comment]
> Would this only be for comp?

@kassibuss A server-side convar to toggle clan tags, less of comp vs non-comp more for server-ops choice but generally for comp
