### ISSUE TITLE
Therm-optic capacity is always correct after switching class

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#270]
when playing as a recon and then changing to assault, the thermo-optic limit is 13 instead of 8 like it usually is for an assault. Upon using the thermo-optic camo, it resets to 8 once it has been fully recharged. -NuclearCat

Players still spawn before selecting a weapon, leading to bugs such as switching from recon to assault leading to assault having 13 of therm-optic camo. - Wakfu

So the more durable way of doing this is probably to check which class the player is and then set thermoptic limits at spawntime (maybe this is a good place to check whether the player is support and if so remove the knife also?), the easy fix is to just never spawn anyone until they've chosen a weapon, which kind of does fix it, but then changing class while still alive during preptime will reintroduce this bug. - Bla

**Comment by nullsystem** [comment]
@blaberry Already fixed in https://github.com/NeotokyoRebuild/neo/commit/30962bf1f612d565f48f9da9a6aca683c4b9adb3 See comment: https://github.com/NeotokyoRebuild/neo/pull/252#issuecomment-2120921117

**Comment by blaberry** [comment]
Cool cool, just need to link the PR
