### ISSUE TITLE
Gun model doesn't dissappear for players when someone is spectating them

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#271]
Gun model disappears (might be related to spectating? ) - StellaNova

to fix the view model (when someone spec in first person mode) the timer should last longer - Syz666

Weapon viewmodels disappeared when someone first person spectated you - Kinoko

Viewmodel sometimes disappears, appears, does whatever it wants. Seemingly related to spectators (first-person spec)? - Wakfu

**Comment by nullsystem** [comment]
Need reproducible test case otherwise might be hard to work on.

**Comment by blaberry** [comment]
This seems to have been fixed. I wouldn't know where to look for a PR that fixes it. Will close as done if no one nominates a PR within a week.

**Comment by kassibuss** [comment]
Should be closed

**Comment by blaberry** [comment]
Have not found PR, will close :(
