### ISSUE TITLE
Crouching still has actors making footsteps sounds

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#275]
crouching silences your steps - muffin_dono

**Comment by Rainyan** [comment]
In original NT, footsteps will play if you are:
* Standing and moving at velocity of >90 ups
* Crouching and moving at velocity of >60 ups

Do we have consensus on whether this should follow parity?

**Comment by blaberry** [comment]
Yes, this should simply follow parity.

**Comment by Rainyan** [comment]
Closing in favor of #363 as this isn't parity.

**Comment by Rainyan** [comment]
Reopening because closed incorrectly.
