### ISSUE TITLE
Spectators can't bodyblock bullets

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#279]
Seeing and shooting spectators. - Bauxite

My dead body spawns on killer. -Izotop

(i think this was related to the ragdoll of who ever just died spawning on who they start spectating) - StellaNova

![Image](https://github.com/NeotokyoRebuild/neo/assets/159314831/7ba564d7-5ad0-42e4-b0ff-d024e29a0388)

While I was using motion vision I could see a t-posing NSF recon that was holding a pistol inside of a friendly assault that was using cloak. - Izotop

**Comment by blaberry** [comment]
This has been resolved, we couldn't reproduce it. But I couldn't find a PR for it, sadly.

**Comment by kassibuss** [comment]
Close?
