### ISSUE TITLE
Enemy ghost carrier is marked red instead of their team color from the perspective of a player

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#280]
Enemy ghost carrier has their respective team colored marker as opposed to the intended red circle. - Kinoko

The ghost holder marker isn't colored red when held by an enemy team (I thought zync fixed that and had a branch for that?) - Wakfu

(should be fixed a few hours after test iirc) -StellaNova

**Comment by nullsystem** [comment]
@kassibuss This is already fixed by reverting a mistake that took it out: https://github.com/NeotokyoRebuild/neo/commit/5bfbd95a82e7f88279ee4fe865cbb44e3e319c17
