### ISSUE TITLE
Viewmodels don't move around weirdly on linux clients connected to dedicated servers when ADSing

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#284]
https://files.catbox.moe/4lf3dq.mp4

*(embedding the video link here into github, in case that link ever goes down, should this issue become relevant at some later point for something -Rain)*

https://github.com/NeotokyoRebuild/neo/assets/6595066/698028e8-7153-4051-93cd-a0d2bbe72ce1

-Wakfu

**Comment by nullsystem** [comment]
Maybe fixed by: https://github.com/NeotokyoRebuild/neo/pull/327
