### ISSUE TITLE
Toggling ADS happens onclick instead of onrelease

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#285]
Toggle ADS should enable on press of the button, not on release of it (this is how it's like in OGNT) - Wakfu

**Comment by Agiel** [comment]
Actually, we're at parity now when it triggers on release, but I agree it should be changed to on click. And a lot of people would like an option to hold instead of toggle.

**Comment by Agiel** [comment]
No I still think ADS should happen on click even if it isn't parity. I'm sure most would agree? We can change the milestone to plugin parity 😉. https://github.com/softashell/nt-sourcemod-plugins/blob/master/scripting/nt_inputtweaks.sp

**Comment by kassibuss** [comment]
Oh, right. Classic me not reading things, yeah having it on click would be better. Sorry 😅
