### ISSUE TITLE
Players are allowed to select their initial weapon outside of freezetime

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#287]
### Description

In OGNT, the player does not spawn until they select a weapon. After roughly 30 seconds (including freeze time) the player gets forcefully spawned with the weapon they played with last round.
In NT;RE, you can only select and receive a weapon during freeze time.

### Issue

With the way the weapon selection works currently, people who aren't paying attention or are AFK during the freeze time will only get their secondary, which has proven to be a confusing and annoying mechanic.

### Proposed solution

Return the weapon selection to back how it is in OGNT

**Comment by blaberry** [comment]
Let's rewrite this into a background, issue, solution statement to make it more actionable @kassibuss
