### ISSUE TITLE
Map audio works as intended

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#292]
While playing on envoy I could hear weird wooden sound(wood_box_scrape_rough_loop1 or wood_box_scrape_smooth_loop1) for all round till new one would start. First I heard it on spawn in the begining of the round, second time I heard it while I was spectating an enemy support(DESTROYGIRL) and a third time I heard it while I was spectating two dead bodies, one of them was laying on tachi. - Izotop

**Comment by nullsystem** [comment]
@kassibuss The description is way too vague, also I think sounds, physics, etc.. should only be checked at til the maps are recompiled for Source SDK 2013.

**Comment by kassibuss** [comment]
Yeah, I am not exactly sure what the issue is. Maybe close until we have recompiled maps? I personally have not encountered anything like this.
