### ISSUE TITLE
PZ reloading audio works as intended

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#293]
When my teammate was reloading PZ far away from me I could still hear it like it was near me. - Izotop

**Comment by Rainyan** [comment]
Fwiw, you actually can't hear reload sounds of other players in original NT without plugins. Is this a feature we want to support? The plugin [had some trouble](https://github.com/Rainyan/sourcemod-nt-audible-reloads/blob/ab5df04f071c6bab8bc4ce178263ea5a387b5c21/addons/sourcemod/scripting/nt_audible_reloads.sp#L14-L16) with the sound directionality as well, this might be related.

**Comment by kassibuss** [comment]
> Fwiw, you actually can't hear reload sounds of other players in original NT without plugins. Is this a feature we want to support? The plugin [had some trouble](https://github.com/Rainyan/sourcemod-nt-audible-reloads/blob/ab5df04f071c6bab8bc4ce178263ea5a387b5c21/addons/sourcemod/scripting/nt_audible_reloads.sp#L14-L16) with the sound directionality as well, this might be related.

I assume the issue meant the little beep sound that plays for the players during thw pz reloading animation, like how ejecting the mag from the jitte(-s) emits a sound.

**Comment by Rainyan** [comment]
> @Rainyan I assume the issue meant the little beep sound that plays for the players clientside during the pz reloading animation, like how ejecting the mag from the jitte(-s) emits a sound.

Yes, but to my knowledge those beeps are not audible in original NT to other players either; they probably just stick out from the more typical reload noises. I'm assuming the reload sfx weren't really made with directional usage in mind, which is why it sounds so off when trying to use them as such.

**Comment by blaberry** [comment]
Let's close this.
