### ISSUE TITLE
Player gibs work on dedicated servers

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#296]
zwia mentioned that the players corpse doesnt get gibbed - Kinoko

**Comment by Rainyan** [comment]
Unable to reproduce. Are we sure this isn't completed by #245 ?

**Comment by nullsystem** [comment]
I believe it is already fixed by that PR. Pinging @AdamTadeusz to close this to confirm.

**Comment by blaberry** [comment]
This is a dupe, closing.
