### ISSUE TITLE
All chat text has a default color tag, leading to no coloration bleed from previous messages being colored

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#298]
The chat colors are sometimes bugged (colors from previous chat messages apply to next ones, probably need to set color tags for text that doesn't have em, which makes them get colored by previous text). - Wakfu

**Comment by nullsystem** [comment]
Give reproducible example steps.

**Comment by blaberry** [comment]
Not sure what leads to it happening, but here's an example

![Image](https://github.com/NeotokyoRebuild/neo/assets/7058830/30f0aa61-880b-498a-8ad5-8382b52e51c7)

**Comment by blaberry** [comment]
Another example, might be separate issues. 

![Image](https://github.com/NeotokyoRebuild/neo/assets/7058830/ecdb9f98-9256-4f48-90bc-201aa714e368)

**Comment by blaberry** [comment]
No obvious way of reproducing this.

**Comment by AdamTadeusz** [comment]
I think its connected to fake nicknames, I can reproduce it by using the single character 'a' as my fake nickname but not other single characters 
![image](https://github.com/user-attachments/assets/262d5e93-eaf3-4475-bbf4-51ae7a2c0fb6)

**Comment by AdamTadeusz** [comment]
![image](https://github.com/user-attachments/assets/b198ffd2-6789-4c25-ab5f-10637f778c2a)
Also here is another one. Easy to see what is going on now (this might not be the only issue, since this shouldn't have broken @blaberry 's second example)
