### ISSUE TITLE
The bullet counter works without modification to the source files

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#299]
The bullet counter in the ammo hud isn't correctly aligned by default due to using original neotokyo's HudLayout.res (because its now left aligned instead of being right aligned). - Wakfu

**Comment by nullsystem** [comment]
I think it's already aligned back to "normal". Pinging: @AdamTadeusz to close it if so.

**Comment by AdamTadeusz** [comment]
I don't get notified of pings in issues for whatever reason but yeah this is fixed now
