### ISSUE TITLE
Crash bug on opening scoreboard/spectator GUI after changing resolution

### ISSUE THREAD

**Issue by nullsystem** [NeotokyoRebuild/neo#333]
* To reproduce:
    1. Open NT;RE, Create Server, enter some map
    2. Spawn in, then press tab, opening the scoreboard + spectator GUI
    3. Esc, go to settings and change the resolution, can be any different resolution (EX: from 900p to 720p)
    4. After it changed, go back to the game and press tab, but this time it crashes the game
* Crash happens in SpectatorGUI when exiting the function
    * Error message: "Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention."
* This is replicated in v5, some commits in between that and 13e08c16d277a059bf8a364b2b179319e9d33e82
* This is not replicable using the VPC + vcproj build system
* EDIT: This also happens on Linux, not really cmake's fault, and seems to be a dangling pointer issue as rain's suggestion

**Comment by Rainyan** [comment]
Can verify this also occurs at commit 17ef464

**Comment by Rainyan** [comment]
Potentially dangling pointers at https://github.com/NeotokyoRebuild/neo/blob/13e08c16d277a059bf8a364b2b179319e9d33e82/mp/src/game/client/game_controls/SpectatorGUI.cpp#L562-L563
