### ISSUE TITLE
Incorrect muzzle flash by Tachi viewmodel

### ISSUE THREAD

**Issue by Rainyan** [NeotokyoRebuild/neo#365]
Not (directly) related to the new muzzle flashes of #334 

### Description

The Tachi pistol's viewmodel fires a muzzle flash positioned such that it looks correct from the first-person view, but when viewed with `thirdperson`, the illusion is broken and it's way off the barrel.

[tachi.webm](https://github.com/NeotokyoRebuild/neo/assets/6595066/b35d054a-d829-4c41-a9d9-be3ccbef12b2)

* You can briefly see the ball of fire near the floor, where the bullets are hitting.
* **Note** that the correct muzzle flash coming from the tip of the pistol in this video is the one from #334 , and is completely unrelated to this bug!

### Steps to repro
* Spawn as assault and equip the Tachi
* Go to `thirdperson`, and then `thirdperson_mayamode` for a better angle.
* Shoot some bullets

### What happens
* Ball of fire placed in the world, such that it appears correct in first person, but is positioned incorrectly in third person.

### What should happen
* This muzzle flash should not be happening at all, because we are (or will be) creating our muzzleflashes using #334 instead.

### Notes
* As this is probably viewmodel related, this incorrect effect is only visible to the player themselves, and it's only apparent in thirdperson mode (however, it will be overlapping with #334 effects once they are merged).
* Third person observers are not affected.
* The Tachi is the only gun with this bug.

**Comment by AdamTadeusz** [comment]
https://github.com/user-attachments/assets/7e7999bc-5faf-484c-a5b1-71f7aba5f5e5

Silencing this DispatchMuzzleEffect in c_baseanimating does the trick
