### ISSUE TITLE
[BUG] Assertion hit if switching guns when aimed in

### ISSUE THREAD

**Issue by Rainyan** [NeotokyoRebuild/neo#398]
### Build Info

20240624_8d02776

### Description

Only affects debug builds.

If you switch to a gun that cannot be aimed-in with (knife, grenades...) while already aiming another gun, an assertion failure is hit at `game/client/hud_crosshair.cpp:272`.

A pragmatic solution would be to just silence the assert, but it might be prudent to investigate why we're hitting it in the first place and solve the root cause instead.

### To Reproduce

* Build a debug build
* Spawn in a level
* Aim in with any weapon
* Switch to your knife or a grenade whilst still aimed in

### Expected behavior

Nothing dramatic happens.

### Actual behavior

A debug assertion is hit.

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

10

**Comment by AdamTadeusz** [comment]
I think this has been fixed

**Comment by VantoNortim** [comment]
> I think this has been fixed

I have just tested this and it is fixed.
