### ISSUE TITLE
[BUG] Round state hud off-center after resolution change

### ISSUE THREAD

**Issue by nullsystem** [NeotokyoRebuild/neo#405]
### Build Info

96f57bed41f9607377521292c952d691696270d0

### Description

When the player changes the screen resolution, the round state hud which is usually centered, becomes off-centered as it retained the previous resolution's central position instead of updating.

### To Reproduce

1. Open game -> Create Server -> Go in
2. Spawn in
3. Change resolution to something smaller

### Expected behavior

Round state hud is still centered

### Actual behavior

Round state hud no longer looks centered, still retains position from previous resolution

### Operating System

- [ ] Windows
- [X] Linux

### Version/Distro

Arch Linux

**Comment by Rainyan** [comment]
Related: #414
