### ISSUE TITLE
[BUG] Crash to Desktop 

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#413]
### Build Info

Build datetime: 2024-06-29T16:37:06Z Git hash: 96f57bed41f9607377521292c952d691696270d0 

### Description

Windows crash dump from the 29.06.2024 playtest

### To Reproduce

not reproducable

### Expected behavior

Game should not crash

### Actual behavior

Game crashed

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

10

### Additional context and Screenshots

[crash_hl2.exe_20240629205759_1.dmp](https://github.com/user-attachments/files/16041977/crash_hl2.exe_20240629205759_1.dmp)

**Comment by Rainyan** [comment]
This is `pOwner` nullptr dereference at https://github.com/NeotokyoRebuild/neo/blob/321f1393c1f60eaddac594029c6fe2ec8bd36b5f/mp/src/game/client/hl2mp/clientmode_hl2mpnormal.cpp#L200

**Comment by Rainyan** [comment]
Possible duplicate: #283
