### ISSUE TITLE
[BUG] Class can be changed freely in an empty server

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#415]
### Build Info

Build datetime: 2024-06-29T16:37:06Z Git hash: 96f57bed41f9607377521292c952d691696270d0

### Description

Currently, when you join an empty server, spawn in and open the class selection menu, the class will change instantly to the one you pick. This is not how it is in the current iteration of Neotokyo. In that, selecting a class while you are will not result in your class changing instantly.

### To Reproduce

1. Join an empty server
2. Join a team
3. Spawn in
4. Open the class selection menu (F2)
5. Select any of the classes

### Expected behavior

Your class will not change whilst you are alive 

### Actual behavior

Your class changes when you pick a class that is not the same as your current class

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

10

**Comment by Rainyan** [comment]
While not parity, being able to undo incorrect class picks feels like an upgrade. Although I suppose we could add a cvar for stricter behaviour. We already have `sv_neo_can_change_classes_anytime` which could maybe be repurposed to accept more enumerations?

**Comment by AdamTadeusz** [comment]
I think that's unnecessary. Just keep the current behaviour and close this issue imo

**Comment by kassibuss** [comment]
Closing this for now since it seems its better to keep the current behavior, if we want to bring it back to parity ill reopen
