### ISSUE TITLE
[FEATURE] Return the damage overlay to the same as in current NT

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#416]
### Description

Currently, the build of NT;RE lacks the same red overlay you get when you are hit by another player. Instead, there are damage indicators depending from which side you got hit from. This makes it hard to discern when you take damage, because there is no visual feedback.

### Proposed Solution

Return back to the same overlay

**Comment by nullsystem** [comment]
There's actually a red overlay if you've like EX: in skyline jump right into the heli blade, that'll show the red overlay. So seems to be there but very high threshold at the moment.

**Comment by AdamTadeusz** [comment]
Yeah I specifically did that as a bandaid fix to remove the red overlay when moving to a spectator view after dying

**Comment by AdamTadeusz** [comment]
Can return the overlay now and test again, we've changed how the spectator works quite a bit so this might not be an issue anymore

**Comment by kassibuss** [comment]
Fixed by #532

**Comment by kassibuss** [comment]
Fix has been merged, closing the issue.
