### ISSUE TITLE
[BUG] While spectating a player holding the ghost in first person spectator mode, the ghost beacon can be seen in their view

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#421]
### Build Info

Build datetime: 2024-06-29T16:37:06Z Git hash: 96f57bed41f9607377521292c952d691696270d0

### Description

Title

### To Reproduce

1. Be in spectator
2. Spectate a player who is holding the ghost in first person mode

### Expected behavior

You should not be able to see the ghost beacon

### Actual behavior

You see the ghost beacon in the player's view

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Windows 10

**Comment by nullsystem** [comment]
First person spec can also see friendly hud on target player, and ghost beacon including spectator, with 0M if spec from spectator or enemy.
