### ISSUE TITLE
[BUG] The score counter in the scoreboard reflects the amount of (team)kills the respective team has gotten instead of round wins.

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#424]
### Build Info

Build datetime: 2024-06-29T16:37:06Z Git hash: 96f57bed41f9607377521292c952d691696270d0

### Description

On the scoreboard, instead of displaying the rounds an X team has won, it instead shows the amount of kills the team you play in has gathered. It even counts the teamkills and adds them to the score. 

### To Reproduce

1. Join server
2. Play the game

### Expected behavior

The score counter on the scoreboard for both teams show the round they have won

### Actual behavior

The score counter on the scoreboard for both teams displays the kills instead

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Windows 10

### Additional context and Screenshots

![image](https://github.com/NeotokyoRebuild/neo/assets/81193965/db6e96df-aac1-4c75-8314-18c82c1f2bce)
In this image, I killed 2 of the NSF bots and teamkilled one Jinrai bot and the scoreboard shows Jinrai having 3 score. This happens both when launching a map from the "Create server" menu or from console.

**Comment by nullsystem** [comment]
Now that's weird, I thought that fix...
@kassibuss  Wait a min, that's not the latest 321f139...

**Comment by kassibuss** [comment]
Okay talking with marter, this is already fixed, feel free to close

**Comment by nullsystem** [comment]
keep it a bit so I'll test it before closing to double check

**Comment by Agiel** [comment]
The screenshot is very clearly not from master.

**Comment by nullsystem** [comment]
Yeah this is an issue with the Windows v6 build. Closed
