### ISSUE TITLE
[BUG] New team/round/timer part of the HUD can become unresponsive after playing a few rounds

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#425]
### Build Info

Build datetime: 2024-06-29T16:37:06Z Git hash: 96f57bed41f9607377521292c952d691696270d0

### Description

Title, this is fixed by restarting the game

### To Reproduce

1. Join a server
2. Play

### Expected behavior

Everything should work as intended, the timer/player counter on hud should be responsive and react to changes.

### Actual behavior

The timer/round counter can become unresponsive.

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Windows 10

**Comment by nullsystem** [comment]
Closed as dupe: #414
