### ISSUE TITLE
[BUG] [PARITY] Can shoot while using ladders (can't in OG)

### ISSUE THREAD

**Issue by xedmain** [NeotokyoRebuild/neo#431]
### Build Info

20240629_321f139

### Description

In NT;RE, you can shoot while using ladders. In OG NT, while using ladders, your gun instead enters the same animation as when sprinting, and you can't shoot it.

### To Reproduce

1. Go up to a ladder
2. Use it (walk into it, up it, w/e)
3. Gun is still in the default animation and you can shoot it

### Expected behavior

While using ladders, the gun is in the same animation as when sprinting and you can't shoot it.

### Actual behavior

While using ladders, the gun is still in the default animation and you can shoot it.

### Operating System

- [ ] Windows
- [X] Linux

### Version/Distro

Arch

### Build's compiler

GNU 10.3.0

**Comment by AdamTadeusz** [comment]
I think it would be cool if we could disable primary weapon use on ladders, but still allow using secondaries on ladders
