### ISSUE TITLE
[BUG] Needs testing! - Players are flailing about erratically in third person, for some reason

### ISSUE THREAD

**Issue by xedmain** [NeotokyoRebuild/neo#432]
### Build Info

20240629_321f139

### Description

For some reason, sometimes, players are faliling about erratically out in third person. Their animations are just broken, some players' anims aren't though.

### To Reproduce

1. Join multiplayer game
2. Look at a player near you
3. Sometimes their animations are broken and they are all erratic

### Expected behavior

Their animations are fine

### Actual behavior

They're erratic and glitched

### Operating System

- [ ] Windows
- [X] Linux

### Version/Distro

Arch

### Build's compiler

GNU 10.3.0

### Additional context and Screenshots

Needs better testing + a recording, but other people during the playtest (2024-06-29) also noted this bug.

**Comment by AdamTadeusz** [comment]
This is caused in part by neo player inheriting both a CBasePlayerAnimState and a CPlayerAnimstate, through their hl2mp_player and INEOPlayerAnimState. Could use an overhaul based on TonySergi's fixes

**Comment by AdamTadeusz** [comment]
You can place a breakpoint in CNEO_Player's PostThink() call m_pPlayerAnimState->Update(RAD2DEG(flYaw), RAD2DEG(flPitch));, and CHL2MP_Player's PostThink() call m_PlayerAnimState.Update(); to see the two different playeranimstates in action. Placing breakpoints that continue code execution and print properties of the animation states shows discrepancies in the two

**Comment by blaberry** [comment]
Dupe of https://github.com/NeotokyoRebuild/neo/issues/121 ?
