### ISSUE TITLE
[BUG] Vision modes are sometimes broken on linux

### ISSUE THREAD

**Issue by xedmain** [NeotokyoRebuild/neo#438]
### Build Info

20240629_321f139

### Description

Sometimes, the vision modes shaders are broken on linux and they're either completely black, or the colors are all wack.

### To Reproduce

Unreproducible

### Expected behavior

Normal vision modes

### Actual behavior

Broken vision modes

### Operating System

- [ ] Windows
- [X] Linux

### Version/Distro

Arch

### Additional context and Screenshots

Needs screenshots, but @nullsystem had the same problem as well

**Comment by nullsystem** [comment]
Note to self: Is this a release mode/broken by optimizer thing?

**Comment by Rainyan** [comment]
From some limited empirical testing on my own machine, this seems to fix it at least for me:

* In the game's root folder (where the gameinfo.txt is), delete the generated `glshaders.cfg` file, if it exists.
* Launch the game to main menu.
* Close the game.
* Verify that in the root folder, a new `glshaders.cfg` has been generated.
* Make that file read-only: `chmod 444 ./glshaders.cfg`.
* Launch the game and verify vision shaders work for all 3 classes.
* If broken, delete the `glshaders.cfg` and start over from step 1, until you get working shaders (undo the read-only with e.g. `chmod 644 ./glshaders.cfg` to be able to delete the file)
* Once you have working shaders, and the file is write-protected, the shaders shouldn't get corrupted anymore.

I don't know why this happens or if this is a universal fix, but I can't reproduce the bug anymore after following these steps. I'm guessing it might have something to do with whatever state is being cached here somehow getting corrupted over multiple restarts of the game.

Would be curious to hear if this works for others using Linux.

**Comment by nullsystem** [comment]
@Rainyan Seems like that works. It seems the cache is rather inconsistent/varied anyway (some having like 3 items, some like 50). It seems to me that file can just be this:
```
"glshadercachev002"
{
}
```
And read-only and it seems to also just work out due to no cache? It also looks like it generates at the end, maybe it could be programatically worked-around by being early enough to delete that file as a potentional work around to not need read-only. Although just a guess.

**Comment by Rainyan** [comment]
> It also looks like it generates at the end, maybe it could be programatically worked-around by being early (or late) enough to delete/overwrite that file as a potentional work around to not need read-only. Although just a guess.

I quickly tried this in `CHLClient::Init`, as soon as we've acquired the `IFileSystem*` from the factory, by calling `->RemoveFile("./glshaders", "MOD");` but that seemed to be too late as I was still sporadically seeing the bug when testing with multiple restarts. But maybe this would be viable at an earlier entry point, perhaps using std functions if we don't have a filesystem interface pointer available yet. Could be worth exploring.

But if are able to track the file's write permissions somehow with Git, then that might be a simpler solution.
