### ISSUE TITLE
Enemy ghost markers do not scale similarly to the current version of NT

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#441]
### Build Info

Build datetime: 2024-06-29T16:37:06Z Git hash: 96f57bed41f9607377521292c952d691696270d0

### Description

In the current version of NT;RE, the enemy markers you see while holding the ghost scale upwards while closer to an enemy and downwards while away from an enemy. It should be the opposite. Also, the distance markers should be on the side, not at the bottom.

### To Reproduce

1. Pick up ghost
2. Look at the enemy markers

### Expected behavior

Far away enemies have a larger icon and close up enemies have smaller ones. 

### Actual behavior

The enemies close to you have huge markers and far away ones have smaller ones.

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Windows 10

### Additional context and Screenshots

Pictures for comparison, NT;RE at the top and current NT at the bottom. Also, I think the font for the "x M" marker isn't 1:1.
![image](https://github.com/NeotokyoRebuild/neo/assets/81193965/65f754c0-8143-474e-b4e0-dfc6149813aa)
![20240630154853_1](https://github.com/NeotokyoRebuild/neo/assets/81193965/cf57517e-0a7f-488d-a29e-d59edaaeb4be)

**Comment by AdamTadeusz** [comment]
![image](https://github.com/NeotokyoRebuild/neo/assets/44210793/8b7c7fc0-229a-4382-866b-ec07ed7034e1)
There doesn't seem to be any scaling of the markers in the original. In the original they do however fade in and out depending on the distance

**Comment by AdamTadeusz** [comment]
I think it's from 35m to 45m that the opacity falls from like 90% to 0%. I think they remain at the 90% opacity or so even at 0m

**Comment by kassibuss** [comment]
> ![image](https://private-user-images.githubusercontent.com/44210793/347826725-8b7c7fc0-229a-4382-866b-ec07ed7034e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3Mjg4NDYsIm5iZiI6MTcyMDcyODU0NiwicGF0aCI6Ii80NDIxMDc5My8zNDc4MjY3MjUtOGI3YzdmYzAtMjI5YS00MzgyLTg2NmItZWMwN2VkNzAzNGUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDIwMDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYmNmY2VhYWY1Y2VkZDg5ZWM1OTFkYTE3MGRiNTMxYzU4YzNmOGI0ODMzN2NhMWMxYmZhY2EzZGY0YjExMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aApMJl8k-GBk0yi2xCh6FOyUUJTFMyrrhCarCA66mMU) There doesn't seem to be any scaling of the markers in the original. In the original they do however fade in and out depending on the distance

youre right, guess i was imagining it 😅
