### ISSUE TITLE
Hud background opacity should be the same as OG NT

### ISSUE THREAD

**Issue by Agiel** [NeotokyoRebuild/neo#455]
### Build Info

20240629_321f139

### Description

OG NT:
![image](https://github.com/NeotokyoRebuild/neo/assets/1762051/46a929a5-9a1b-4f87-87db-572e42e3ae27)

NT;RE:
![image](https://github.com/NeotokyoRebuild/neo/assets/1762051/609fa6d3-6aa7-4d24-a1d6-21ab5f4695d1)

### To Reproduce

Launch into a map, spawn on a team and observer the HUD.

### Expected behavior

The HUD background opacity should match OG NT.

### Actual behavior

It's much less transparent.

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Windors 10

**Comment by AdamTadeusz** [comment]
Against either a totally white or a totally black background, an rgba value of 200 200 200 40 gives the same background colour as in the original. unfortunately this colour seems a little too opaque on more varied backgrounds
![image](https://github.com/user-attachments/assets/5a3a70ac-39dc-48c8-845c-924d14622a93)

**Comment by AdamTadeusz** [comment]
I used https://stackoverflow.com/questions/12228548/finding-equivalent-color-with-opacity to get the value of 226 226 226 63 in the middle, but must have messed something up as it was only correct for the white background, and then I experimented with the values until I got something that was spot on for the white and black, which also happens to have a very nice rounded rgba value
