### ISSUE TITLE
Round-end graphics have a drop shadow

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#472]
This would make then universally legible against brighter areas that occur on some maps.

Round end graphics being the "JINRAI WINS" text and "X captured the ghost" text for example.

**Comment by AdamTadeusz** [comment]
Might be impossible ngl

**Comment by nullsystem** [comment]
I think it just render it twice, one black one white

**Comment by AdamTadeusz** [comment]
> I think it just render it twice, one black slight offset then one white

The ISurface functions DrawPrintText and DrawTexturedRect add the rgb values of whatever is being drawn to the screen, so an rgb value of 0, 0, 0 has no effect.

**Comment by nullsystem** [comment]
> The ISurface functions DrawPrintText and DrawTexturedRect add the rgb values of whatever is being drawn to the screen, so an rgb value of 0, 0, 0 has no effect.


![backdropfonthting](https://github.com/NeotokyoRebuild/neo/assets/15316579/fe849820-8ffc-4468-944b-feccb4eed4fd)

**Comment by AdamTadeusz** [comment]
> > The ISurface functions DrawPrintText and DrawTexturedRect add the rgb values of whatever is being drawn to the screen, so an rgb value of 0, 0, 0 has no effect.
> 
> @AdamTadeusz
> 
> ![backdropfonthting](https://private-user-images.githubusercontent.com/15316579/347633781-fe849820-8ffc-4468-944b-feccb4eed4fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTU5MDAsIm5iZiI6MTcyMDY5NTYwMCwicGF0aCI6Ii8xNTMxNjU3OS8zNDc2MzM3ODEtZmU4NDk4MjAtOGZmYy00NDY4LTk0NGItZmVjY2I0ZWVkNGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDExMDAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzYzU3NGZkZDAzMDNmMzhmMjNiNTk4ZWY1YmQzOTk2MWYyMjM5OTBkZDY4OTZkMjZmZWYxZmQwNDc4YWUyN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.INAVl5vxlElmgQTIXWthbK4wPELOcsaK5v89Vu3t3U0)
> 
> EDIT: I'll explain, it's because they're marked as "additive" then 0,0,0 end up being invisible. Remove that additive flags from both the font and texture, then the color worked as normal and 0,0,0 is black on screen as expected.

![Kneelgeta](https://github.com/NeotokyoRebuild/neo/assets/44210793/5f7aa2a5-a142-4ab1-9db5-1fe19dbb7e65)
