### ISSUE TITLE
Crouched movement jittery

### ISSUE THREAD

**Issue by AdamTadeusz** [NeotokyoRebuild/neo#478]
### Build Info

[20240704][2da1c6d]

### Description

Movement jittery when crouched, player starts and stops moving repeatedly although velocity remains constant

### To Reproduce

Open up any map
Pick any class
Pick any loadout
Enable sv_cheats 1
Set host_timescale to 0.1 to see the problem more clearly
Move in any direction while crouched

### Expected behavior

Character moves smoothly

### Actual behavior

Character movement is jittery

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

11

### Build's compiler

MSVC 19.40.33811.0

**Comment by Rainyan** [comment]
This fixes the pred error spam for ducked movement, but we're still getting a mismatch for `cl_showerror 2` at location `setpos 1382.033203 1579.425659 183.281250;setang 13.991999 -3.431316 0.0` of nt_dimensions_test map, trying to duck under the panel between the pre-placed translucent ducked assault & recon models when you are an assault. This would probably be worth fixing here as well, and making sure the recon/support don't have a similar off by one unit discrepancy between cli/srv.

**Comment by Rainyan** [comment]
Meant to comment at #480
