### ISSUE TITLE
Verify: Console is clean and readable and team win is not spammed in chat

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#48]

**Comment by blaberry** [comment]
This seems fixed in the latest release. Some minor error messages but no major issues with massive spam. 

![Image](https://github.com/user-attachments/assets/55e348a7-5259-4791-8c15-cf9b26378503)

**Comment by blaberry** [comment]
@nullsystem assuming you fixed this somewhere? can I reassign it to you?

**Comment by nullsystem** [comment]
No idea, it's kinda vague any fixes that happens overtime "fixes" this issue anyway
