### ISSUE TITLE
Viewmodels animate at low FPS on dedicated servers that have been running non-stop for a long time

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#507]
### Build Info

20240629_96f57be

### Description

I joined wakfus server, a week or two since last playtest. The viewmodel sinusoidal idle swaying animation was running at like 2fps. I tried firing my gun and the server and client crashed right away.

### To Reproduce

1. Wait for dedicated server to go without a restart(and mapchange? I don't know) for a while
2. Spawn in
3. observe low rendering fps on the viewmodel
4. (optional) shoot gun to crash game

### Expected behavior

No low animation framerate on the viewmodel sway.

### Actual behavior

There was low framerate on the viewmodel. The rest of the game ran fine.

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Win 10

### Machine's CPU

Ryzen 9 7950X

### Machine's GPU

RTX 3080 FE

### GPU's driver

Nvidia 556.12

### Build's compiler

MSVC 19.37.32825.0

### Additional context and Screenshots

neo_version (Client's build info):
Build version: 20240629_96f57be
Build datetime: 2024-06-29T16:37:06Z
Git hash: 96f57bed41f9607377521292c952d691696270d0
OS: Windows
Compiler: MSVC 19.37.32825.0

**Comment by kassibuss** [comment]
Closing since this is fixed by just restarting or voting a new map
