### ISSUE TITLE
Player hud shows up for spectators

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#508]
### Build Info

20240629_96f57be

### Description

The integrity/cloak/aux and ammo hud sections from first person shows up when you spectate a player.

![image](https://github.com/user-attachments/assets/6d7a4ab2-eaef-4574-9bc0-af6e19091eb5)

### To Reproduce

1. Join a game as spectator
2. Wait for new round start
3. When new round starts, you'll see the integrity/cloak/aux and ammo hud sections from first person

### Expected behavior

The integrity/cloak/aux and ammo hud sections from first person don't show up

### Actual behavior

The integrity/cloak/aux and ammo hud sections from first person shows up

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Win 10

**Comment by nullsystem** [comment]
Can also just load up a demo file and that'll reproduce it also.
