### ISSUE TITLE
Text in menus are readable on stream

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#52]
**Issue:** 
Default SDK2013 menu text is quite small. This makes it hard to read for viewers of a stream.

**Solution:**
This could be fixable with a thicker font or with larger size. 

**Note:**
There's a PR for a new menu system, so this will probably be resolved in that PR with new menus.

**Comment by nullsystem** [comment]
Closed since there's already the "new menu system"?

**Comment by blaberry** [comment]
Sounds good to me
