### ISSUE TITLE
Water doing 10 damage per hit instead of 7

### ISSUE THREAD

**Issue by AdamTadeusz** [NeotokyoRebuild/neo#530]
### Build Info

75f1e63

### Description

Water doing 10 damage per hit instead of 7

### To Reproduce

Download and launch the map breakwater
Jump in the water

### Expected behavior

After some time the character starts taking 10 damage per drown tick

### Actual behavior

Character takes 7 damage per drown tick

### Operating System

- [ ] Windows
- [ ] Linux

### Version/Distro

11

**Comment by nullsystem** [comment]
@AdamTadeusz Are you sure you're not mixing whatever that section of breakwater's map that damages 7hp? If you hold long enough staying still at some wall it does damage 10hp.

**Comment by nullsystem** [comment]
Actually the water damage doesn't seem so replicable? Probably more of an issue with the damager not being activated?

**Comment by AdamTadeusz** [comment]
There's a place on shrine with some water under the little bridge, just enough to drown yourself, I'll test with the version compiled to work in ntre tomorrow I guess

**Comment by nullsystem** [comment]
ok I know what, AUX = 0 means water damage starts happening. Which the fix for the anti-drain masked that as I was running with the fix in. So basically another case of de-couple the aux from water damage.

**Comment by nullsystem** [comment]
Updated PR #557 to fix for this also

**Comment by nullsystem** [comment]
@AdamTadeusz Might want to update this about AUX tied to underwater damage instead of 7 vs 10hp thing

**Comment by AdamTadeusz** [comment]
@nullsystem wouldn't that make this a duplicate of #529? Maybe just close this instead?

**Comment by nullsystem** [comment]
@AdamTadeusz It's slightly different imo, or that can add info about not relying on 0-aux to start drowning

**Comment by AdamTadeusz** [comment]
https://github.com/user-attachments/assets/232d05bc-480a-4410-8919-eacedbe1d335
@nullsystem
