### ISSUE TITLE
[BUG] Ghost holder's icon is ahead of player's movement

### ISSUE THREAD

**Issue by brysondev** [NeotokyoRebuild/neo#536]
### Build Info

20240801-9d04458

### Description

Ghost holder's HUD icon moves ahead of the player's movements. So leaning left and moving left results in an icon slightly ahead of the player's actual position. Alternating left and right lean while moving makes icon sway a lot more than OG.

### To Reproduce

Pickup ghost and lean while walking in front of viewer.

### Expected behavior

Ghost marker should be accurate to the player's position.

### Actual behavior

Ghost marker is ahead of the player when leaning and walking by several units

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Windows 11

### Machine's CPU

AMD Ryzen 9 5900X

### Machine's GPU

NVIDIA GeForce RTX 3080 Ti

### Additional context and Screenshots

[ghost_indicator.webm](https://github.com/user-attachments/assets/3fec9e38-b3af-4708-a02b-93086f62f74b)

**Comment by nullsystem** [comment]
#476 Might fixes as indirectly as it moves the icon position to fetch from local ghost PVS
