### ISSUE TITLE
Firing guns should not draw tracers from the players own viewmodel

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#548]
### Build Info

20240629_96f57be

### Description

Currently, if you fire a weapon there are client side tracers drawn simulating bullets flying out of your gun

### To Reproduce

1. Shoot gun
2. See tracer

### Expected behavior

No tracers for first person shots

### Actual behavior

There are tracers

### Operating System

- [X] Windows
- [X] Linux

### Version/Distro

Win 10

**Comment by AdamTadeusz** [comment]
Should the tracers be visible coming out of your own gun in thirdperson? And what about when using cl_first_person_uses_world_model?

**Comment by blaberry** [comment]
I think limiting it do when drawing the viewmodels is fine. That's parity behaviour afaik. Should probably be tested though.
