### ISSUE TITLE
Correct Aux draining speed for Recons

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#55]

**Comment by nullsystem** [comment]
@blaberry Need details, cause I thought it's ok when it drains 45aux per jump.

**Comment by blaberry** [comment]
Yeah that's correct, this was already fixed in an earlier PR that fixed most or all of the flaws with recon stats and I think we just missed connecting this issue with that pr

**Comment by blaberry** [comment]
Yeah that's correct, this was already fixed in an earlier PR that fixed most or all of the flaws with recon stats and I think we just missed connecting this issue with that pr
