### ISSUE TITLE
Reloads from other people are audible

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#583]
### Build Info

20240914_b2291c5

### Description

Sometimes when other players reload guns the reloads can be heard. That doesnt happen in the original nt

### To Reproduce

1. Play game

### Expected behavior

Reloads from other people should not be audible

### Actual behavior

Reloads from other people are audible

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Win 10

### Build's compiler

MSVC 19.41.3

### Additional context and Screenshots

Maybe keep in?

**Comment by AdamTadeusz** [comment]
I remember @blaberry mention we used to bait people with reload sounds. Does that mean actually in the original game reload sounds are in fact audible to other players?

**Comment by blaberry** [comment]
Pretty sure I've been doing so under the mistaken assumption that people were being baited, while they heard nothing 😅

**Comment by AdamTadeusz** [comment]
In that case ill start a discussion, since we have a PR that will make reload sounds audible to everyone without them playing with no direction

**Comment by AdamTadeusz** [comment]
Close since arguably bad game mechanic and we now have https://github.com/NeotokyoRebuild/neo/pull/610 ?
