### ISSUE TITLE
Sounds for specific actions are not audible at times

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#584]
### Build Info

20240914_b2291c5

### Description

Some actions do not play a sound when they should be playing one, e.g an explosion from a nade or when picking up the ghost

### To Reproduce

1. Have teammate/yourself/enemy pick up the ghost or have someone throw a nade

### Expected behavior

Sounds for the respective actions should play

### Actual behavior

They do not

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

win 10

### Build's compiler

MSVC 19.41.3

**Comment by nullsystem** [comment]
Too unspecific, list out specific steps to reproduce for a ghost pick up.

**Comment by AdamTadeusz** [comment]
Specifically grenade explosion sounds are unreliable, unless you have line of sight of a grenade or explosion, often explosions that are just around the corner that you should definitely be able to hear just do not make any noise

**Comment by AdamTadeusz** [comment]
I personally have had a few instances where I walk around the corner to see an explosion effect dying down, but it makes no sound because I couldn't yet see the effect when the sound began to play
