### ISSUE TITLE
[FEATURE] Cancel button in the Root Menu's Options

### ISSUE THREAD

**Issue by xedmain** [NeotokyoRebuild/neo#590]
### Description

Currently, when exiting the options after having modified something but not applied, this screen is shown:
![image](https://github.com/user-attachments/assets/7c2fa9e9-0953-446f-8997-59e3201380c1)
As it stands, it's impossible to go back to options. You can only either save the modified settings (which you might not even remember) or discard them.

### Proposed Solution

![image](https://github.com/user-attachments/assets/97cd9580-c03a-417e-bf34-4a327e403842)
I propose adding a "Cancel" button, with which the user will be able to go back to the options in case they have accidentally clicked the back button, or if they had forgotten/want to verify what they modified.
Additionally, since discarding is a destructive action, I think it's better to have the escape key focus the new "Cancel" button, so that in case the user that accidentally goes back and panics and presses the escape button doesn't erase all of their modifications.

**Comment by nullsystem** [comment]
@xedmain What about just Save and Cancel, removing Discard entirely. Just simpler.

**Comment by nullsystem** [comment]
> > @xedmain What about just Save and Cancel, removing Discard entirely. Just simpler.
> 
> what are you supposed to do then if you dislike the modifications you have made? in place of the discard button, a revert button that reverts settings to the version before unsaved modifications in the options themselves (in the same row as BACK, LEGACY buttons) could be added I guess (or have them both). Also there's no "Reset to Defaults" button too

@xedmain It's already there, called "Restore" 2nd button from the right next to "Accept" in that row.
But yes there's no Defaults button yet.
