### ISSUE TITLE
Grenades show wrong killerinfo weapon

### ISSUE THREAD

**Issue by Rainyan** [NeotokyoRebuild/neo#596]
### Build Info

v8.0-prealpha (b2291c5)

### Description

Grenade kills incorrectly display the attack weapon as the weapon currently held by the attacker, not the grenade itself.

### To Reproduce

* Join a local server as assault
* Spawn in a bot
* Set `bot_mimic 1; bot_attack 0`
* Switch your gun to grenade, so the bot will also
* Set `bot_mimic 0`, throw away your own grenade somewhere safe
* Turn `bot_mimic 1` on again
* Make the bot net a grenade kill on you

### Expected behavior

Killerinfo panel shows the name of the weapon currently held by the bot as the attack weapon, and not the grenade's name.

### Actual behavior

Killerinfo panel shows the grenade's name as the attack weapon.

### Operating System

- [ ] Windows
- [X] Linux

### Version/Distro

Mint 21.3 Cinnamon

### Additional context and Screenshots

[killerinfo.webm](https://github.com/user-attachments/assets/c7e3c57f-e06a-424f-ba4d-885f07f00e24)

**Comment by AdamTadeusz** [comment]
In the case of thrown projectiles like grenades the weapon used to spawn the grenade projectile is usually deleted by the time the projectile kills a player. In those cases the easiest value to return that would be meaningful to the person who died would be the class name of the projectile returned by GetInflictor()
![image](https://github.com/user-attachments/assets/93d83acc-0a67-46be-8b56-a3bd87af8cfb)
Could also match the class name of the projectile to some expected values to make it look nicer than neo_grenade_frag for example

**Comment by AdamTadeusz** [comment]
you mean plugins can actually read this information in this box?
If so, do you know what the og nt name for detpacks and frags is?

**Comment by Rainyan** [comment]
https://wiki.alliedmods.net/Neotokyo_Events
