### ISSUE TITLE
Root NeoUI - Settings missing "Default" reset button

### ISSUE THREAD

**Issue by nullsystem** [NeotokyoRebuild/neo#612]
There isn't a button to reset all the settings back to the default ones. Although when this button is clicked, make sure to have a popup dialog so it guards from the user mistakenly clicking on it and double-check if they really want to reset to default.

**Comment by AdamTadeusz** [comment]
"I <Insert steam nickname here> acknowledge this action will clear all custom settings"

**Comment by nullsystem** [comment]
Turning it to a typing test lol
