### ISSUE TITLE
[Server] Changing levels to nt_shrine_ctg causes segfault

### ISSUE THREAD

**Issue by brysondev** [NeotokyoRebuild/neo#621]
### Build Info

20240919_9e83cc3

### Description

Changing levels on a dedicated linux server to `nt_shrine_ctg` causes a segfault. I've attached a crash dump for analysis. It likely happens with maps with displacements, but I cannot confirm that.

### To Reproduce

1. Start server on map that doesn't crash upon launch.
2. Change map to `nt_shrine_ctg` (or anything presumably with displacements [unverified])
3. Server segfaults immediately.

### Expected behavior

Server should be able to host `nt_shrine_ctg` without crashing.

### Actual behavior

Server segfaults and reboots.

### Operating System

- [ ] Windows
- [X] Linux

### Version/Distro

Debian GNU/Linux bookworm 12.7, Kernel Linux 6.1.0-25-amd64

### Machine's CPU

11th Gen Intel(R) Core(TM) i9-11900K

### Build's compiler

GNU 11.4.0

### Additional context and Screenshots

[0c51477b-fd37-4f08-8c99b8a7-94fbf829.dmp.txt](https://github.com/user-attachments/files/17066774/0c51477b-fd37-4f08-8c99b8a7-94fbf829.dmp.txt)
[0c51477b-fd37-4f08-8c99b8a7-94fbf829.dmp](https://github.com/user-attachments/files/17066775/0c51477b-fd37-4f08-8c99b8a7-94fbf829.dmp)

**Comment by brysondev** [comment]
We might want to collect a list of maps that cause segfaulting, #592 is related.

**Comment by Rainyan** [comment]
Would it be worthwhile to convert all of the "Map X crashes" issues into this meta issue: https://github.com/NeotokyoRebuild/neoAssets/issues/1 ? Because trying to forward-port the old maps to be fully compatible might not be a worthwhile venture, if we can simply solve it by recompiling.

**Comment by AdamTadeusz** [comment]
I agree, having all these separate issues just makes filtering through them harder, when the solutions to all these issues is the same and is described best in https://github.com/NeotokyoRebuild/neoAssets/issues/1

**Comment by brysondev** [comment]
Someone should close all of them and reference that issue.

**Comment by AdamTadeusz** [comment]
Closed in favor of https://github.com/NeotokyoRebuild/neoAssets/issues/1
