### ISSUE TITLE
Snowfall elevator sequence is timed incorrectly

### ISSUE THREAD

**Issue by Rainyan** [NeotokyoRebuild/neo#627]
### Build Info

v8.1-prealpha (9e83cc3)

### Description

On the map `nt_snowfall_ctg_b12` ([download link](https://gamebanana.com/mods/141026)), the round begins too early (the `GO GO GO` HUD announcement & players unfrozen) for the elevator spawn side to exit the elevator. This breaks map timings and ruins the chokepoint balance.

I'm unsure whether this is an elevator movement speed issue or a problem with the freezetime/spawn timings.

### To Reproduce

* Join a server with the map `nt_snowfall_ctg_b12`
* Spawn on the elevator side of the map for a new round

### Expected behavior

As soon as the HUD displays the `GO GO GO` and you're unfrozen, you can exit the elevator and continue to the earliest contact points in the map unhindered.

### Actual behavior

The `GO GO GO` HUD message is displayed, and teams are unfrozen to move freely while you are still stuck inside the elevator, waiting for it to lower enough to allow exiting. This breaks timings and makes your spawn largely unfavourable for that round.

### Operating System

- [ ] Windows
- [X] Linux

### Version/Distro

Linux Mint 21.3 Cinnamon

### Additional context and Screenshots

[ntre_snowfall_b12_elevator.webm](https://github.com/user-attachments/assets/458d771d-f322-45e1-8277-643b781b31a6)

**Comment by AdamTadeusz** [comment]
crazy getting out of the elevator only for Majestic to already be in your face

**Comment by AdamTadeusz** [comment]
Looks like the pre-round freeze is about 3 seconds shorter in rebuild, Elevator moves at the same speed and characters start off at the same altitude

**Comment by AdamTadeusz** [comment]
I just noticed that once the round goes live it is 2:35 minutes long as well, where as in the original it is 3:00 minutes long.

Meaning currently rounds in NEOTOKYO are 3:13 minutes long with freeze time, and 2:45 minutes long in Rebuild

**Comment by AdamTadeusz** [comment]
A 15 second pre round freeze makes more sense, and feels right timing wise in the elevator
