### ISSUE TITLE
Settings menu is modified to include all the new settings under multiple tabs

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#64]
In the multiplayer tab: 
- Fakenick
- Steam names settings
- Spray toggle

In a new, "game" tab:
- Reload when empty
- Hold to aim
- show pos
- third person view model
- right handed view model
- FOV settings

![Image](https://github.com/user-attachments/assets/49000a7a-b368-49a7-86b0-a9aa12054f0d)

![Image](https://github.com/user-attachments/assets/4f51d5a4-c1f2-462b-b893-804023e80e99)

**Comment by nullsystem** [comment]
This should be renamed to something else + description on what's wanted instead. Agiel's asset loading fix fixes settings menu loading which means we can edit it directly now.
Probably neo_name related + sprays settings put in there at least.

**Comment by nullsystem** [comment]
I don't think there's much customization that can be done with the multiplayer settings tab beyond the controls it gives (sprays, crosshair, model, download opts, advanced button). It's not really defined in the given source code so while it's possible to add widgets via res file, it can't really use them. At best at the moment, just remove the model section. If the slider widget can be fixed, then the crosshair stuff it gives can also be used.

**Comment by blaberry** [comment]
Yeah we might want to redefine this, but I'm not sure exactly how to break it down

**Comment by nullsystem** [comment]
@blaberry Considering I'm currently instead doing a replacement/override of the root panel, then this kind of thing can just be done under that instead.

**Comment by nullsystem** [comment]
Closing this, replaced by issue #542 (PR #539)
