### ISSUE TITLE
Weapon view models behaving weirdly when sprinting

### ISSUE THREAD

**Issue by AdamTadeusz** [NeotokyoRebuild/neo#703]
Specifically the tachi, zr68l and milso. Need to test all weapons for this.

**Comment by brysondev** [comment]
https://github.com/user-attachments/assets/bec75e14-2c2d-41d9-9be0-a69aad29865f

**Comment by kassibuss** [comment]
Tested all of the weapons, besides the aforementioned ones, only the zrs seems to share the same behavior

**Comment by AdamTadeusz** [comment]
Seems that the behaviour is caused by the current vm sequence being set to the transition sequence towards the activity ACT_IDLE. Since none of the breakpoints at all calls to set the current activity to ACT_IDLE get hit when sprinting, its likely that something is instead changing the current sequence to the idle sequence directly, and then the code that calculates the most appropriate current activity changes the activity to a transition activity.

**Comment by AdamTadeusz** [comment]
This is another one of those problems that goes away if the window isn't in focus, unless you are moving your cursor

https://github.com/user-attachments/assets/4902ff73-403b-48a9-b9c2-8695072a57e9
