### ISSUE TITLE
oilstain barrels should not be physics objects

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#72]

**Comment by kassibuss** [comment]
This is not actually an issue AFAIK, it is just that because of the physics differences in the engine, the barrels react with more moving. Close? @blaberry

**Comment by blaberry** [comment]
Maybe close, though we could arguably look at modifying the prop physics or maybe changing the collision groups of props. Specifically on rise you can bump your head and _take damage_ from sprinthopping into the lamps on roof spawn

**Comment by AdamTadeusz** [comment]
No amount of shooting or running into or exploding any props on the original can make them move. In my opinion the ability to do so in the rebuild is a straight up upgrade, makes the gameplay deeper as you can barricade doorways or use props to reach new places.
![image](https://github.com/user-attachments/assets/831e278c-5fd1-4a9d-8afe-6224cb425239)

An easy way to make the props not move is to set their movetype to none. Doing this as soon as they spawn means that some props will float, can instead do this once they have settled, for example once freeze time is over. Props with the movetype MOVETYPE_FLYGRAVITY will ignore players and bullets but will still react to gravity, though this generates a lot of assertion failures ( though non of them seemingly game-breaking? )

**Comment by kassibuss** [comment]
I think keeping the barrels as is would be okay, its a pretty non-issue in my eyes mow tbh. The more important issue is players taking damage from props if they bhop into them like the lamp on the rise spawn stairs as @blaberry mentioned

**Comment by AdamTadeusz** [comment]
It's a question for the design doc I guess. Players probably shouldn't be immune to damage from collisions with moving objects, which don't exist in the original so we have nothing to compare the current system to.

**Comment by blaberry** [comment]
can't we simply mark them as debris?

**Comment by AdamTadeusz** [comment]
From the initial testing I did that didnt seem to do anything, but maybe the collision group was changed somewhere further down back to something else

**Comment by kassibuss** [comment]
Closing in favor of https://github.com/NeotokyoRebuild/neoAssets/issues/1
