### ISSUE TITLE
Assertion hit when using the m41l

### ISSUE THREAD

**Issue by AdamTadeusz** [NeotokyoRebuild/neo#728]
Not a major problem since none of the loadouts have an m41l, but if using a command to give yourself an m41l, the assertion at
weapon_neobasecombatweapon.cpp (651) is hit
![image](https://github.com/user-attachments/assets/4812f74a-23a2-4c67-97b6-9206ed3f250e)

**Comment by AdamTadeusz** [comment]
maybe double check the pbk works as well. You will need to enable the compile argument to compile with the pbk

**Comment by brysondev** [comment]
- M41L has muzzle flash through suppressor
- Spread appears to be inverse of what it should be

I changed `option(NEO_BUILD_WEAPON_PBK56S "Build PBK56S weapon" ON)` in the cmake, but I don't know if that's what you meant.

Walking through the code it can't find the `GetNeoWepBits()` for the M41L.

**Comment by Masterkatze** [comment]
That will change the default option to ON, to turn it on - configure CMake with `-DNEO_BUILD_WEAPON_PBK56S=ON` or turn it in your IDE depending on what you use.

**Comment by brysondev** [comment]
Ty Masterkatze.

Looks like the `handlingTable[]` was missing the M41L. Making a PR now...
