### ISSUE TITLE
Friendly indicators don't show up after using x-ray mode

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#783]
### Build Info

20241102_14c4282

### Description

The little friendly player icons stay hidden on next round if you used xray mode in spectate on the previous round

### To Reproduce

1. Die
2. Spectate
3. Turn on xray
4. Conclude round
5. Look for friendly indicators

### Expected behavior

You see friendly indicators on friendlies

### Actual behavior

Indicators are gone

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Win 10

### Machine's CPU

Ryzen 9 7950X

### Machine's GPU

RTX 3080 FE

### GPU's driver

Nvidia 556.12

### Build's compiler

MSVC 19.41.34123.0

**Comment by kassibuss** [comment]
*DEAD* rain: if you have the wallhack spec thing enabled, press X to turn it off before the round ends
*DEAD* rain: and you get the IFF icons for next round
*

**Comment by kassibuss** [comment]
![image](https://github.com/user-attachments/assets/463c85ac-19f1-4672-9ddd-4af58ddd678f)
![image](https://github.com/user-attachments/assets/c7a8be87-ef3d-4a5f-a0c1-716906daaa7a)
It will also offset the IFF if you forget to change it back (the screenshots are from a spectators POV, but if you spawn the round afterwards, it will have the same effect)
