### ISSUE TITLE
[BUG] Fade to black on death does not work properly

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#794]
### Build Info

20241102_14c4282

### Description

When you die to another player on a server, the fade to black does not seem to work properly. In an offline match, if you do kill in console or die to your own grenade it seems to work.

### To Reproduce

1. Die to another player

### Expected behavior

Before you get put into spectator, you get the fade to black screen and then become a spectator

### Actual behavior

You instantly become a spectator 

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

10

**Comment by Rainyan** [comment]
Possibly related: https://github.com/NeotokyoRebuild/neo/pull/380#discussion_r1643552882
