### ISSUE TITLE
NEOUI nullpointer exception

### ISSUE THREAD

**Issue by AdamTadeusz** [NeotokyoRebuild/neo#814]
Some commands like the cl_showfps command do not have guards for the minimum and maximum value. Setting the value of such a command outside of the expected range via the console causes a null pointer exception when opening the options menu since there's no label for the current out of range value for that command

To Reproduce:
run the command "cl_showfps 3" in the console
open the menu and click on "options"

Expected outcome: Options menu opens

Actual outcome: nullptr exception

**Comment by AdamTadeusz** [comment]
@nullsystem I'll tag you since this is probably something you've worked on, can take a look at it myself if you don't want to

**Comment by nullsystem** [comment]
@AdamTadeusz I guess just enforcing the min-max range or reset to default inside NeoUI should be enough to fix it.
