### ISSUE TITLE
Attachments of cloaked players cast shadows

### ISSUE THREAD

**Issue by Rainyan** [NeotokyoRebuild/neo#831]
### Build Info

d40ea92

### Description

When a player cloaks, their shadow is not rendered. However, the attached items such as pistol, grenades etc. keep casting their shadows even in the cloaked state, when they shouldn't.

### To Reproduce

* Join a local map
* Spawn a bot: `bot_add`
* Use `bot_mimic 1`
* Cloak yourself, so the bot also cloaks
* Observe the bot's shadow

### Expected behavior

In the cloaked state, the bot casts no shadow whatsoever.

### Actual behavior

In the cloaked state, the bot still casts its attachments' shadows.

### Operating System

- [ ] Windows
- [X] Linux

### Version/Distro

Linux Mint 21.3 Cinnamon

### Machine's CPU

AMD Ryzen 5 7600

### Machine's GPU

AMD RX 580

### GPU's driver

Mesa 23.2.1-1ubuntu3.1~22.04.2

### Build's compiler

gcc (Ubuntu 11.4.0-1ubuntu1~22.04)

### Additional context and Screenshots

![nt_dimensions_test0002](https://github.com/user-attachments/assets/1c914d99-5d40-4db3-83aa-63e1776ac3be)

**Comment by AdamTadeusz** [comment]
https://github.com/user-attachments/assets/5b32a031-6e9a-4c4b-83c2-fa1b52c2f658

Annoying that it sometimes does work
