### ISSUE TITLE
The amount of throwables you may carry matches legacy

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#94]

**Comment by kassibuss** [comment]
This should be fixed? @blaberry

**Comment by blaberry** [comment]
Yep, just need to link it to a pr

**Comment by kassibuss** [comment]
Closing this for now since the values for the nades seem to be the same and there is no PR..? Feel free to reopen

**Comment by blaberry** [comment]
I can't link it for some godforsaken reason but it's https://github.com/NeotokyoRebuild/neo/pull/246
